/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.LetterType;
import business.Lot;
import java.util.Calendar;

/**
 *
 * @author Олеся
 */
public class SellerLotPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerLotPanel
     */
    public SellerLotPanel(Lot lot,MainSellerFrame dialog) {
        this.lot = lot;
        this.dialog = dialog;
        initComponents();
        
        setLot();
    }
    
    private void setLot(){
        this.lblName.setText(lot.getName());
        this.lblCost.setText(lot.getPrice() + " r");
        double dateFinish = Math.rint(100*((lot.getFinishDate().getTimeInMillis() - Calendar.getInstance().getTimeInMillis()) / 3600000))/100;
        this.lblFinishTime.setText(dateFinish + " hours");
        if(dateFinish <= 0 && lot.getStatus() && lot.getCustomer()!=null){
            this.lblStatus.setText("Buyed");
            this.btnConfirm.setEnabled(true);
        } else if(dateFinish > 0 && lot.getStatus()){
            this.lblStatus.setText("Confirmed");
        } else {
            this.lblStatus.setText("In verification");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblFinishTime = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("name");

        lblCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCost.setText("cost");

        lblFinishTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFinishTime.setText("time to finish");

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setText("status");

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCost, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinishTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblCost)
                    .addComponent(lblFinishTime)
                    .addComponent(lblStatus)
                    .addComponent(btnConfirm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        dialog.dispose();
        new LetterFrame(lot, LetterType.USERMESSAGE).setVisible(true);
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblFinishTime;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    private Lot lot;
    private MainSellerFrame dialog;
}
